DROP TABLE WYPOZYCZENIA CASCADE CONSTRAINTS;
DROP TABLE PANSTWO CASCADE CONSTRAINTS;
DROP TABLE WOJEWODZTWO CASCADE CONSTRAINTS;
DROP TABLE MIASTO CASCADE CONSTRAINTS;
DROP TABLE KLIENT CASCADE CONSTRAINTS;
DROP TABLE PRACOWNIK CASCADE CONSTRAINTS;
DROP TABLE WYPOZYCZALNIA CASCADE CONSTRAINTS;
DROP TABLE RODZAJ_PLATNOSCI CASCADE CONSTRAINTS;
DROP TABLE PRODUCENT CASCADE CONSTRAINTS;
DROP TABLE MODEL CASCADE CONSTRAINTS;
DROP TABLE KOLOR CASCADE CONSTRAINTS;
DROP TABLE TYP_NAPEDU CASCADE CONSTRAINTS;
DROP TABLE PAKIET_WYPOSAZENIA CASCADE CONSTRAINTS;

---------------------------------------------------------------
CREATE TABLE KLIENT (
    ID NUMBER(5) PRIMARY KEY,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL
);

CREATE TABLE PANSTWO (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE WOJEWODZTWO (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL
);

CREATE TABLE MIASTO (
    ID NUMBER(4) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL
);

CREATE TABLE RODZAJ_PLATNOSCI (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);


CREATE TABLE PRODUCENT (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE MODEL (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE KOLOR (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE TYP_NAPEDU (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE PAKIET_WYPOSAZENIA (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE PRACOWNIK (
    ID NUMBER(5) PRIMARY KEY,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL
);

CREATE TABLE WYPOZYCZALNIA (
    ID NUMBER(5) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL 
);

CREATE TABLE wypozyczenia (
    ID NUMBER(6) NOT NULL PRIMARY KEY,
    -- KLIENT
    ID_KLIENT NUMBER(5) NOT NULL,
    ID_PANSTWO_KLIENT NUMBER(3) NOT NULL,
    ID_WOJEWODZTWO_KLIENT NUMBER(3) NOT NULL,
    ID_MIASTO_KLIENT NUMBER(4) NOT NULL,
    
    -- RODZAJ_PLATNOSCI
    ID_RODZAJ_PLATNOSCI NUMBER(2) NOT NULL,
    
    -- SKUTER
    ID_PRODUCENT NUMBER(2) NOT NULL,
    ID_MODEL NUMBER(3) NOT NULL,
    ID_KOLOR NUMBER(2) NOT NULL,
    ID_TYP_NAPEDU NUMBER(2) NOT NULL,
    ID_PAKIET_WYPOSAZENIA NUMBER(2) NOT NULL,
    POJEMNOSC NUMBER(5,2) NOT NULL CHECK (POJEMNOSC > 0),
    ROK_PRODUKCJI NUMBER(4) NOT NULL CHECK (ROK_PRODUKCJI >= 1900),
    
    -- PRACOWMNIK / WYPOZYCZALNIA
    ID_PRACOWNIK NUMBER(5) NOT NULL,
    ID_WYPOZYCZALNIA NUMBER(5) NOT NULL,
    ID_PANSTWO_WYPOZYCZENIA NUMBER(3) NOT NULL,
    ID_WOJEWODZTWO_WYPOZYCZENIA NUMBER(3) NOT NULL,
    ID_MIASTO_WYPOZYCZENIA NUMBER(4) NOT NULL,
    
    
    CENA NUMBER(6,2) NOT NULL CHECK (CENA > 0),
    ROK_WYPOZYCZENIA NUMBER(4) NOT NULL,
    MIESIAC_WYPOZYCZENIA NUMBER(2) NOT NULL,
    ROK_ODDANIA NUMBER(4) NOT NULL,
    MIESIAC_ODDANIA NUMBER(2) NOT NULL,
    
    CONSTRAINT FK_WYPOZYCZENIA_KLIENT FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID),
    CONSTRAINT FK_WYPOZYCZENIA_PANSTWO_KLIENT FOREIGN KEY (ID_PANSTWO_KLIENT) REFERENCES PANSTWO(ID),
    CONSTRAINT FK_WYPOZYCZENIA_WOJEWODZTWO_KLIENT FOREIGN KEY (ID_WOJEWODZTWO_KLIENT) REFERENCES WOJEWODZTWO(ID),
    CONSTRAINT FK_WYPOZYCZENIA_MIASTO_KLIENT FOREIGN KEY (ID_MIASTO_KLIENT) REFERENCES MIASTO(ID),
    
    CONSTRAINT FK_WYPOZYCZENIA_RODZAJ_PLATNOSCI FOREIGN KEY (ID_RODZAJ_PLATNOSCI) REFERENCES RODZAJ_PLATNOSCI(ID),
    
    CONSTRAINT FK_WYPOZYCZENIA_PRODUCENT FOREIGN KEY (ID_PRODUCENT) REFERENCES PRODUCENT(ID),
    CONSTRAINT FK_WYPOZYCZENIA_MODEL FOREIGN KEY (ID_MODEL) REFERENCES MODEL(ID),
    CONSTRAINT FK_WYPOZYCZENIA_KOLOR FOREIGN KEY (ID_KOLOR) REFERENCES KOLOR(ID),
    CONSTRAINT FK_WYPOZYCZENIA_TYP_NAPEDU FOREIGN KEY (ID_TYP_NAPEDU) REFERENCES TYP_NAPEDU(ID),
    CONSTRAINT FK_WYPOZYCZENIA_PAKIET_WYPOSAZENIA FOREIGN KEY (ID_PAKIET_WYPOSAZENIA) REFERENCES PAKIET_WYPOSAZENIA(ID),
    
    CONSTRAINT FK_WYPOZYCZENIA_PRACOWNIK FOREIGN KEY (ID_PRACOWNIK) REFERENCES PRACOWNIK(ID),
    CONSTRAINT FK_WYPOZYCZENIA_WYPOZYCZALNIA FOREIGN KEY (ID_WYPOZYCZALNIA) REFERENCES WYPOZYCZALNIA(ID),
    CONSTRAINT FK_WYPOZYCZENIA_PANSTWO_WYPOZYCZENIA FOREIGN KEY (ID_PANSTWO_WYPOZYCZENIA) REFERENCES PANSTWO(ID),
    CONSTRAINT FK_WYPOZYCZENIA_WOJEWODZTWO_WYPOZYCZENIA FOREIGN KEY (ID_WOJEWODZTWO_WYPOZYCZENIA) REFERENCES WOJEWODZTWO(ID),
    CONSTRAINT FK_WYPOZYCZENIA_MIASTO_WYPOZYCZENIA FOREIGN KEY (ID_MIASTO_WYPOZYCZENIA) REFERENCES MIASTO(ID)
);
