DROP TABLE WYPOZYCZENIA CASCADE CONSTRAINTS;
DROP TABLE PLATNOSC CASCADE CONSTRAINTS;
DROP TABLE PRACOWNIK CASCADE CONSTRAINTS;
DROP TABLE KLIENT CASCADE CONSTRAINTS;
DROP TABLE SKUTER CASCADE CONSTRAINTS;

----------------------------------------------------------------------------------------

CREATE TABLE KLIENT (
    ID NUMBER(5) PRIMARY KEY,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    DATA_URODZENIA DATE NOT NULL,
    NR_TELEFONU CHAR(9) NOT NULL,
    NR_LOKALU NUMBER(4) NOT NULL,
    -- ADRES
    ID_ULICA NUMBER(5) NOT NULL,
    ULICA VARCHAR2(50) NOT NULL,
    ID_MIASTO NUMBER(4) NOT NULL,
    MIASTO VARCHAR2(50) NOT NULL,
    ID_WOJEWODZTWO NUMBER(3) NOT NULL,
    WOJEWODZTWO VARCHAR2(50) NOT NULL,
    ID_PANSTWO NUMBER(3) NOT NULL,
    PANSTWO VARCHAR2(50) NOT NULL
);

CREATE TABLE PRACOWNIK (
    ID NUMBER(5) PRIMARY KEY,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    NR_TELEFONU CHAR(9) NOT NULL,
    --WYPOZYCZALNIA
    ID_WYPOZYCZALNIA NUMBER(5) NOT NULL,
    WYPOZYCZALNIA VARCHAR2(50) NOT NULL,
    NR_LOKALU NUMBER(4) NOT NULL,
    ID_ULICA NUMBER(5) NOT NULL,
    ULICA VARCHAR2(50) NOT NULL,
    ID_MIASTO NUMBER(4) NOT NULL,
    MIASTO VARCHAR2(50) NOT NULL,
    ID_WOJEWODZTWO NUMBER(3) NOT NULL,
    WOJEWODZTWO VARCHAR2(50) NOT NULL,
    ID_PANSTWO NUMBER(3) NOT NULL,
    PANSTWO VARCHAR2(50) NOT NULL
);

CREATE TABLE PLATNOSC (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL
);

CREATE TABLE SKUTER (
    ID NUMBER(6) PRIMARY KEY,
    ID_MODELU NUMBER(3) NOT NULL,
    MODEL VARCHAR2(50) NOT NULL,
    ID_PRODUCENTA NUMBER(2) NOT NULL,
    PRODUCENT VARCHAR2(50) NOT NULL,
    ID_KOLOR NUMBER(2) NOT NULL,
    KOLOR VARCHAR2(50) NOT NULL,
    ID_TYP_NAPEDU NUMBER(2) NOT NULL,
    TYP_NAPEDU VARCHAR2(50) NOT NULL,
    ID_PAKIET_WYPOSAZENIA NUMBER(2) NOT NULL,
    PAKIET_WYPOSAZENIA VARCHAR2(50) NOT NULL,
    -- SKUTER
    POJEMNOSC NUMBER(5,2) NOT NULL CHECK (POJEMNOSC > 0),
    ROK_PRODUKCJI NUMBER(4) NOT NULL CHECK (ROK_PRODUKCJI >= 1900),
    -- WYPOZYCZALNIA
    ID_WYPOZYCZALNIA NUMBER(5) NOT NULL,
    WYPOZYCZALNIA VARCHAR2(50) NOT NULL,
    NR_LOKALU NUMBER(4) NOT NULL,
    ID_ULICA NUMBER(5) NOT NULL,
    ULICA VARCHAR2(50) NOT NULL,
    ID_MIASTO NUMBER(4) NOT NULL,
    MIASTO VARCHAR2(50) NOT NULL,
    ID_WOJEWODZTWO NUMBER(3) NOT NULL,
    WOJEWODZTWO VARCHAR2(50) NOT NULL,
    ID_PANSTWO NUMBER(3) NOT NULL,
    PANSTWO VARCHAR2(50) NOT NULL
   
);

CREATE TABLE WYPOZYCZENIA (
    ID_KLIENT NUMBER(5) NOT NULL,
    ID_SKUTER NUMBER(6) NOT NULL,
    ID_PRACOWNIK NUMBER(5) NOT NULL,
    ID_PLATNOSC NUMBER(2) NOT NULL,
    DATA_WYPOZYCZENIA DATE NOT NULL,
    DATA_ODDANIA DATE NOT NULL,
    CENA NUMBER(6,2) NOT NULL CHECK (CENA > 0),
    CONSTRAINT FK_WYPOZYCZENIA_KLIENT FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID),
    CONSTRAINT FK_WYPOZYCZENIA_SKUTER FOREIGN KEY (ID_SKUTER) REFERENCES SKUTER(ID),
    CONSTRAINT FK_WYPOZYCZENIA_PRACOWNIK FOREIGN KEY (ID_PRACOWNIK) REFERENCES PRACOWNIK(ID),
    CONSTRAINT FK_WYPOZYCZENIA_PLATNOSC FOREIGN KEY (ID_PLATNOSC) REFERENCES PLATNOSC(ID)
);
