DROP TABLE H_WYPOZYCZENIA CASCADE CONSTRAINTS;
DROP TABLE H_KLIENT CASCADE CONSTRAINTS;
DROP TABLE H_PANSTWO CASCADE CONSTRAINTS;
DROP TABLE H_WOJEWODZTWO CASCADE CONSTRAINTS;
DROP TABLE H_MIASTO CASCADE CONSTRAINTS;
DROP TABLE H_RODZAJ_PLATNOSCI CASCADE CONSTRAINTS;
DROP TABLE H_PRODUCENT CASCADE CONSTRAINTS;
DROP TABLE H_MODEL CASCADE CONSTRAINTS;
DROP TABLE H_KOLOR CASCADE CONSTRAINTS;
DROP TABLE H_TYP_NAPEDU CASCADE CONSTRAINTS;
DROP TABLE H_PAKIET_WYPOSAZENIA CASCADE CONSTRAINTS;
DROP TABLE H_PRACOWNIK CASCADE CONSTRAINTS;
DROP TABLE H_WYPOZYCZALNIA CASCADE CONSTRAINTS;
DROP TABLE H_MIESIAC CASCADE CONSTRAINTS;

---------------------------------------------------------------

CREATE TABLE H_KLIENT (
    ID NUMBER(5) PRIMARY KEY,
    IMIE VARCHAR2(40) NOT NULL,
    NAZWISKO VARCHAR2(40) NOT NULL
);

CREATE TABLE H_PANSTWO (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL UNIQUE
);

CREATE TABLE H_WOJEWODZTWO (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL
);

CREATE TABLE H_MIASTO (
    ID NUMBER(4) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL
);

CREATE TABLE H_RODZAJ_PLATNOSCI (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL UNIQUE
);

CREATE TABLE H_PRODUCENT (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL UNIQUE
);

CREATE TABLE H_MODEL (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL UNIQUE
);

CREATE TABLE H_KOLOR (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL UNIQUE
);

CREATE TABLE H_TYP_NAPEDU (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL UNIQUE
);

CREATE TABLE H_PAKIET_WYPOSAZENIA (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL UNIQUE
);

CREATE TABLE H_PRACOWNIK (
    ID NUMBER(5) PRIMARY KEY,
    IMIE VARCHAR2(40) NOT NULL,
    NAZWISKO VARCHAR2(40) NOT NULL
);

CREATE TABLE H_WYPOZYCZALNIA (
    ID NUMBER(5) PRIMARY KEY,
    NAZWA VARCHAR2(40) NOT NULL 
);


CREATE TABLE H_MIESIAC (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(20) NOT NULL
);

CREATE TABLE H_WYPOZYCZENIA (
    ID_KLIENT NUMBER(5) NOT NULL,
    ID_PANSTWO_KLIENT NUMBER(3) NOT NULL,
    ID_WOJEWODZTWO_KLIENT NUMBER(3) NOT NULL,
    ID_MIASTO_KLIENT NUMBER(4) NOT NULL,
    
    ID_RODZAJ_PLATNOSCI NUMBER(2) NOT NULL,
    
    ID_PRODUCENT NUMBER(2) NOT NULL,
    ID_MODEL NUMBER(3) NOT NULL,
    ID_KOLOR NUMBER(2) NOT NULL,
    ID_TYP_NAPEDU NUMBER(2) NOT NULL,
    ID_PAKIET_WYPOSAZENIA NUMBER(2) NOT NULL,
	POJEMNOSC NUMBER(5,2) NOT NULL CHECK (POJEMNOSC > 0),
    ROK_PRODUKCJI NUMBER(4) NOT NULL CHECK (ROK_PRODUKCJI >= 1900),
    ID_WYPOZYCZALNIA_SKUTER NUMBER(5) NOT NULL,
    ID_PANSTWO_SKUTER NUMBER(3) NOT NULL,
    ID_WOJEWODZTWO_SKUTER NUMBER(3) NOT NULL,
    ID_MIASTO_SKUTER NUMBER(4) NOT NULL,
	
	
    ID_PRACOWNIK NUMBER(5) NOT NULL,
    ID_WYPOZYCZALNIA_PRACOWNIK NUMBER(5) NOT NULL,
    ID_PANSTWO_PRACOWNIK NUMBER(3) NOT NULL,
    ID_WOJEWODZTWO_PRACOWNIK NUMBER(3) NOT NULL,
    ID_MIASTO_PRACOWNIK NUMBER(4) NOT NULL,
    
    CENA NUMBER(6,2) NOT NULL CHECK (CENA > 0),
    ROK_WYPOZYCZENIA NUMBER(4) NOT NULL,
    ID_MIESIAC_WYPOZYCZENIA NUMBER(2) NOT NULL,
    ROK_ODDANIA NUMBER(4) NOT NULL,
    ID_MIESIAC_ODDANIA NUMBER(2) NOT NULL,
    
    CONSTRAINT FK_H_WYPOZYCZENIA_KLIENT FOREIGN KEY (ID_KLIENT) REFERENCES H_KLIENT(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_PANSTWO_KLIENT FOREIGN KEY (ID_PANSTWO_KLIENT) REFERENCES H_PANSTWO(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_WOJEWODZTWO_KLIENT FOREIGN KEY (ID_WOJEWODZTWO_KLIENT) REFERENCES H_WOJEWODZTWO(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_MIASTO_KLIENT FOREIGN KEY (ID_MIASTO_KLIENT) REFERENCES H_MIASTO(ID),
    
    CONSTRAINT FK_H_WYPOZYCZENIA_RODZAJ_PLATNOSCI FOREIGN KEY (ID_RODZAJ_PLATNOSCI) REFERENCES H_RODZAJ_PLATNOSCI(ID),
    
    CONSTRAINT FK_H_WYPOZYCZENIA_PRODUCENT FOREIGN KEY (ID_PRODUCENT) REFERENCES H_PRODUCENT(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_MODEL FOREIGN KEY (ID_MODEL) REFERENCES H_MODEL(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_KOLOR FOREIGN KEY (ID_KOLOR) REFERENCES H_KOLOR(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_TYP_NAPEDU FOREIGN KEY (ID_TYP_NAPEDU) REFERENCES H_TYP_NAPEDU(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_PAKIET_WYPOSAZENIA FOREIGN KEY (ID_PAKIET_WYPOSAZENIA) REFERENCES H_PAKIET_WYPOSAZENIA(ID),
	
    CONSTRAINT FK_WYP_WYPOZYCZALNIA_SKUTER FOREIGN KEY (ID_WYPOZYCZALNIA_SKUTER) REFERENCES H_WYPOZYCZALNIA(ID),
    CONSTRAINT FK_WYP_PANSTWO_SKUTER FOREIGN KEY (ID_PANSTWO_SKUTER) REFERENCES H_PANSTWO(ID),
    CONSTRAINT FK_WYP_WOJEWODZTWO_SKUTER FOREIGN KEY (ID_WOJEWODZTWO_SKUTER) REFERENCES H_WOJEWODZTWO(ID),
    CONSTRAINT FK_WYP_MIASTO_SKUTER FOREIGN KEY (ID_MIASTO_SKUTER) REFERENCES H_MIASTO(ID),
	
    CONSTRAINT FK_H_WYPOZYCZENIA_PRACOWNIK FOREIGN KEY (ID_PRACOWNIK) REFERENCES H_PRACOWNIK(ID),

    CONSTRAINT FK_WYP_WYPOZYCZALNIA_PRACOWNIK FOREIGN KEY (ID_WYPOZYCZALNIA_PRACOWNIK) REFERENCES H_WYPOZYCZALNIA(ID),
    CONSTRAINT FK_WYP_PANSTWO_PRACOWNIK FOREIGN KEY (ID_PANSTWO_PRACOWNIK) REFERENCES H_PANSTWO(ID),
    CONSTRAINT FK_WYP_WOJEWODZTWO_PRACOWNIK FOREIGN KEY (ID_WOJEWODZTWO_PRACOWNIK) REFERENCES H_WOJEWODZTWO(ID),
    CONSTRAINT FK_WYP_MIASTO_PRACOWNIK FOREIGN KEY (ID_MIASTO_PRACOWNIK) REFERENCES H_MIASTO(ID),
    
    CONSTRAINT FK_H_WYPOZYCZENIA_MIESIAC_WYPOZYCZENIA FOREIGN KEY (ID_MIESIAC_WYPOZYCZENIA) REFERENCES H_MIESIAC(ID),
    CONSTRAINT FK_H_WYPOZYCZENIA_MIESIAC_ODDANIA FOREIGN KEY (ID_MIESIAC_ODDANIA) REFERENCES H_MIESIAC(ID)
);
