TRUNCATE TABLE H_WYPOZYCZENIA;
TRUNCATE TABLE H_PANSTWO;
TRUNCATE TABLE H_WOJEWODZTWO;
TRUNCATE TABLE H_MIASTO;
TRUNCATE TABLE H_KLIENT;
TRUNCATE TABLE H_PRACOWNIK;
TRUNCATE TABLE H_WYPOZYCZALNIA;
TRUNCATE TABLE H_RODZAJ_PLATNOSCI;
TRUNCATE TABLE H_PRODUCENT;
TRUNCATE TABLE H_MODEL;
TRUNCATE TABLE H_KOLOR;
TRUNCATE TABLE H_TYP_NAPEDU;
TRUNCATE TABLE H_PAKIET_WYPOSAZENIA;
TRUNCATE TABLE H_MIESIAC;

---------------------------------------------------------------
INSERT INTO H_KLIENT (ID, IMIE, NAZWISKO) SELECT ID, IMIE, NAZWISKO FROM KLIENT;

INSERT INTO H_PANSTWO (ID, NAZWA) SELECT * FROM PANSTWO;
INSERT INTO H_WOJEWODZTWO (ID, NAZWA) SELECT id, nazwa FROM wojewodztwo;
INSERT INTO H_MIASTO (ID, NAZWA) SELECT id, nazwa FROM MIASTO;

INSERT INTO H_RODZAJ_PLATNOSCI (ID, NAZWA) SELECT * FROM rodzaj_platnosci;

INSERT INTO H_PRODUCENT (ID, NAZWA) SELECT * FROM PRODUCENT;
INSERT INTO H_MODEL (ID, NAZWA) SELECT id, nazwa FROM MODEL;
INSERT INTO h_kolor (ID, nazwa) SELECT * FROM kolor;
INSERT INTO H_TYP_NAPEDU (ID, NAZWA) SELECT * FROM TYP_NAPEDU;
INSERT INTO H_PAKIET_WYPOSAZENIA (ID, NAZWA) SELECT * FROM PAKIET_WYPOSAZENIA;

INSERT INTO H_PRACOWNIK (ID, IMIE, NAZWISKO) SELECT ID, IMIE, NAZWISKO FROM PRACOWNIK;

INSERT INTO H_WYPOZYCZALNIA (ID, NAZWA) SELECT ID, NAZWA FROM wypozyczalnia;

INSERT ALL
  INTO H_MIESIAC (ID, NAZWA) VALUES (1, 'styczen')
  INTO H_MIESIAC (ID, NAZWA) VALUES (2, 'luty')
  INTO H_MIESIAC (ID, NAZWA) VALUES (3, 'marzec')
  INTO H_MIESIAC (ID, NAZWA) VALUES (4, 'kwiecien')
  INTO H_MIESIAC (ID, NAZWA) VALUES (5, 'maj')
  INTO H_MIESIAC (ID, NAZWA) VALUES (6, 'czerwiec')
  INTO H_MIESIAC (ID, NAZWA) VALUES (7, 'lipiec')
  INTO H_MIESIAC (ID, NAZWA) VALUES (8, 'sierpien')
  INTO H_MIESIAC (ID, NAZWA) VALUES (9, 'wrzesien')
  INTO H_MIESIAC (ID, NAZWA) VALUES (10, 'pazdziernik')
  INTO H_MIESIAC (ID, NAZWA) VALUES (11, 'listopad')
  INTO H_MIESIAC (ID, NAZWA) VALUES (12, 'grudzien')
SELECT * FROM dual;

INSERT INTO H_WYPOZYCZENIA (ID,
    ID_KLIENT, ID_PANSTWO_KLIENT, ID_WOJEWODZTWO_KLIENT, ID_MIASTO_KLIENT,
    ID_RODZAJ_PLATNOSCI,
    ID_PRODUCENT, ID_MODEL, ID_KOLOR, ID_TYP_NAPEDU, ID_PAKIET_WYPOSAZENIA,
    ID_SKUTER, POJEMNOSC, ROK_PRODUKCJI,
    ID_PRACOWNIK, 
    ID_WYPOZYCZALNIA, ID_PANSTWO_WYPOZYCZENIA, ID_WOJEWODZTWO_WYPOZYCZENIA, ID_MIASTO_WYPOZYCZENIA,
    CENA,
    ROK_WYPOZYCZENIA, ID_MIESIAC_WYPOZYCZENIA,
    ROK_ODDANIA, ID_MIESIAC_ODDANIA
) SELECT w.ID,  
    k.ID, pk.ID, wk.ID, mk.ID,
    w.ID_RODZAJ_PLATNOSCI,
    m.ID_PRODUCENT, sk.ID_MODEL, sk.ID_KOLOR, sk.ID_TYP_NAPEDU, sk.ID_PAKIET_WYPOSAZENIA, 
    w.ID_skuter, sk.POJEMNOSC, sk.ROK_PRODUKCJI,
    w.ID_PRACOWNIK, 
    wy.ID, pw.ID, ww.ID, mw.ID,
    w.CENA,
    EXTRACT(YEAR FROM w.DATA_WYPOZYCZENIA), EXTRACT(MONTH FROM w.DATA_WYPOZYCZENIA),
    EXTRACT(YEAR FROM w.DATA_ODDANIA), EXTRACT(MONTH FROM w.DATA_ODDANIA)
FROM WYPOZYCZENIA w
JOIN KLIENT k ON w.ID_KLIENT = k.ID
JOIN ULICA uk ON k.ID_ULICA = uk.ID
JOIN MIASTO mk ON uk.ID_MIASTO = mk.ID
JOIN WOJEWODZTWO wk ON mk.ID_WOJEWODZTWO = wk.ID
JOIN PANSTWO pk ON wk.ID_PANSTWO = pk.ID
JOIN SKUTER sk ON w.ID_SKUTER = sk.ID
JOIN MODEL m ON sk.ID_MODEL = m.ID
JOIN PRACOWNIK p ON w.ID_PRACOWNIK = p.ID
JOIN WYPOZYCZALNIA wy ON sk.ID_WYPOZYCZALNIA = wy.ID
JOIN ULICA uw ON wy.ID_ULICA = uw.ID
JOIN MIASTO mw ON uw.ID_MIASTO = mw.ID
JOIN WOJEWODZTWO ww ON mw.ID_WOJEWODZTWO = ww.ID
JOIN PANSTWO pw ON ww.ID_PANSTWO = pw.ID;

