-- 2. Zapytanie agreguje przychody z wypozyczen wedlug wypozyczalni, pracownika i metody platnosci.

SELECT 
    NVL(wypo.NAZWA, 'RAZEM - WYPOZYCZALNIA') AS WYPOZYCZALNIA,
    NVL(p.IMIE, 'RAZEM -') || ' ' || NVL(p.NAZWISKO, 'PRACOWNIK') AS PRACOWNIK,
    NVL(r.NAZWA, 'RAZEM - PLATNOSC') AS RODZAJ_PLATNOSCI,
    agg.PRZYCHOD
FROM (
    SELECT 
        wypo.ID AS WYPOZYCZALNIA_ID,
        p.ID AS PRACOWNIK_ID,
        r.ID AS RODZAJ_PLATNOSCI_ID,
        SUM(w.CENA) AS PRZYCHOD
    FROM WYPOZYCZENIA w
        JOIN PRACOWNIK p ON w.ID_PRACOWNIK = p.ID
        JOIN WYPOZYCZALNIA wypo ON p.ID_WYPOZYCZALNIA = wypo.ID
        JOIN RODZAJ_PLATNOSCI r ON w.ID_RODZAJ_PLATNOSCI = r.ID
    GROUP BY ROLLUP(wypo.ID, p.ID, r.ID)
) agg
LEFT JOIN WYPOZYCZALNIA wypo ON agg.WYPOZYCZALNIA_ID = wypo.ID
LEFT JOIN PRACOWNIK p ON agg.PRACOWNIK_ID = p.ID
LEFT JOIN RODZAJ_PLATNOSCI r ON agg.RODZAJ_PLATNOSCI_ID = r.ID
ORDER BY PRZYCHOD;