SELECT ID_PRODUCENT, COUNT(*), SUM(CENA)
FROM H_WYPOZYCZENIA
GROUP BY ID_PRODUCENT
--ORDER BY ID_PRODUCENT;
MINUS
SELECT prod.ID, COUNT(*), SUM(wyp.CENA)
FROM WYPOZYCZENIA wyp
JOIN SKUTER s ON wyp.ID_SKUTER = s.ID
JOIN MODEL m ON s.ID_MODEL = m.ID
JOIN PRODUCENT prod ON m.ID_PRODUCENT = prod.ID
GROUP BY prod.ID
--ORDER BY prod.ID;
