DROP TABLE PANSTWO CASCADE CONSTRAINTS;
DROP TABLE WOJEWODZTWO CASCADE CONSTRAINTS;
DROP TABLE MIASTO CASCADE CONSTRAINTS;
DROP TABLE ULICA CASCADE CONSTRAINTS;

DROP TABLE KLIENT CASCADE CONSTRAINTS;
DROP TABLE WYPOZYCZALNIA CASCADE CONSTRAINTS;

DROP TABLE STATUS_PLATNOSCI CASCADE CONSTRAINTS;
DROP TABLE RODZAJ_PLATNOSCI CASCADE CONSTRAINTS;
DROP TABLE PLATNOSC CASCADE CONSTRAINTS;

DROP TABLE MODEL CASCADE CONSTRAINTS;
DROP TABLE STATUS_SKUTERA CASCADE CONSTRAINTS;
DROP TABLE TYP_NAPEDU CASCADE CONSTRAINTS;
DROP TABLE SKUTER CASCADE CONSTRAINTS;

DROP TABLE STATUS_WYPOZYCZENIA CASCADE CONSTRAINTS;
DROP TABLE WYPOZYCZENIA CASCADE CONSTRAINTS;



    -- TABELE DO ADRESU
CREATE TABLE PANSTWO (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE WOJEWODZTWO (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL,
    ID_PANSTWO NUMBER(10) NOT NULL,
    CONSTRAINT FK_WOJEWODZTWO_PANSTWO FOREIGN KEY (ID_PANSTWO) REFERENCES PANSTWO(ID)
);

CREATE TABLE MIASTO (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL,
    ID_WOJEWODZTWO NUMBER(10) NOT NULL,
    CONSTRAINT FK_MIASTO_WOJEWODZTWO FOREIGN KEY (ID_WOJEWODZTWO) REFERENCES WOJEWODZTWO(ID)
);

CREATE TABLE ULICA (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL,
    ID_MIASTO NUMBER(10) NOT NULL,
    CONSTRAINT FK_ULICA_MIASTO FOREIGN KEY (ID_MIASTO) REFERENCES MIASTO(ID)
);

    -- PODSTAWOWE TABELE DANOWE DO WYPOZYCZEN
CREATE TABLE KLIENT (
    ID NUMBER(10) PRIMARY KEY,
    ID_ULICA NUMBER(10) NOT NULL,
    NR_LOKALU NUMBER(5) NOT NULL,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    DATA_URODZENIA DATE NOT NULL,
    NR_TELEFONU CHAR(9) NOT NULL,
    CONSTRAINT FK_KLIENT_ULICA FOREIGN KEY (ID_ULICA) REFERENCES ULICA(ID)
);

CREATE TABLE WYPOZYCZALNIA (
    ID NUMBER(10) PRIMARY KEY,
    ID_ULICA NUMBER(10) NOT NULL,
    NR_LOKALU NUMBER(5) NOT NULL,
    NAZWA VARCHAR(50) NOT NULL,
    NR_TELEFONU CHAR(9) NOT NULL,
    CONSTRAINT FK_WYPOZYCZALNIA_ULICA FOREIGN KEY (ID_ULICA) REFERENCES ULICA(ID)
);

    -- TABELE PLATNOSCI
CREATE TABLE STATUS_PLATNOSCI (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE RODZAJ_PLATNOSCI (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PLATNOSC (
    ID NUMBER(10) PRIMARY KEY,
    ID_STATUS NUMBER(10) NOT NULL,
    ID_RODZAJ NUMBER(10) NOT NULL,
    CONSTRAINT FK_PLATNOSC_STATUS FOREIGN KEY (ID_STATUS) REFERENCES STATUS_PLATNOSCI(ID),
    CONSTRAINT FK_PLATNOSC_RODZAJ FOREIGN KEY (ID_RODZAJ) REFERENCES RODZAJ_PLATNOSCI(ID)
);

    -- TABELE DLA SKUTERA
CREATE TABLE MODEL (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE STATUS_SKUTERA (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TYP_NAPEDU (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE SKUTER (
    ID NUMBER(10) PRIMARY KEY,
    ID_MODEL NUMBER(10) NOT NULL,
    ID_STATUS NUMBER(10) NOT NULL,
    ID_TYP_NAPEDU NUMBER(10) NOT NULL,
    POJEMNOSC NUMBER(10,2) NOT NULL,
    ROK_PRODUKCJI NUMBER(4) NOT NULL,
    KWOTA NUMBER(10,2) NOT NULL, -- KWOTA ZA WYPOZYCZENIA NA 1h
    CONSTRAINT FK_SKUTER_MODEL FOREIGN KEY (ID_MODEL) REFERENCES MODEL(ID),
    CONSTRAINT FK_SKUTER_STATUS FOREIGN KEY (ID_STATUS) REFERENCES STATUS_SKUTERA(ID),
    CONSTRAINT FK_SKUTER_TYP_NAPEDU FOREIGN KEY (ID_TYP_NAPEDU) REFERENCES TYP_NAPEDU(ID)
);

    -- TABELA DO WYPOZYCZENIA
CREATE TABLE STATUS_WYPOZYCZENIA (
    ID NUMBER(10) PRIMARY KEY,
    NAZWA VARCHAR(50) NOT NULL UNIQUE
);

    -- TABELA FAKTÓW
CREATE TABLE WYPOZYCZENIA (
    ID NUMBER(10) PRIMARY KEY,
    ID_KLIENT NUMBER(10) NOT NULL,
    ID_SKUTER NUMBER(10) NOT NULL,
    ID_WYPOZYCZALNIA NUMBER(10) NOT NULL,
    ID_PLATNOSC NUMBER(10) NOT NULL,
    ID_STATUS NUMBER(10) NOT NULL,
    DATA_WYPOZYCZENIA TIMESTAMP NOT NULL,
    DATA_ODDANIA TIMESTAMP,
    CENA NUMBER(10,2) NOT NULL,
    CONSTRAINT FK_WYPOZYCZENIA_KLIENT FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID),
    CONSTRAINT FK_WYPOZYCZENIA_SKUTER FOREIGN KEY (ID_SKUTER) REFERENCES SKUTER(ID),
    CONSTRAINT FK_WYPOZYCZENIA_WYPOZYCZALNIA FOREIGN KEY (ID_WYPOZYCZALNIA) REFERENCES WYPOZYCZALNIA(ID),
    CONSTRAINT FK_WYPOZYCZENIA_PLATNOSC FOREIGN KEY (ID_PLATNOSC) REFERENCES PLATNOSC(ID),
    CONSTRAINT FK_WYPOZYCZENIA_STATUS FOREIGN KEY (ID_STATUS) REFERENCES STATUS_WYPOZYCZENIA(ID)
);



