DROP TABLE PANSTWO CASCADE CONSTRAINTS;
DROP TABLE WOJEWODZTWO CASCADE CONSTRAINTS;
DROP TABLE MIASTO CASCADE CONSTRAINTS;
DROP TABLE ULICA CASCADE CONSTRAINTS;
DROP TABLE KLIENT CASCADE CONSTRAINTS;
DROP TABLE WYPOZYCZALNIA CASCADE CONSTRAINTS;
DROP TABLE PRODUCENT CASCADE CONSTRAINTS;
DROP TABLE MODEL CASCADE CONSTRAINTS;
DROP TABLE TYP_NAPEDU CASCADE CONSTRAINTS;
DROP TABLE KOLOR CASCADE CONSTRAINTS;
DROP TABLE PAKIET_WYPOSAZENIA CASCADE CONSTRAINTS;
DROP TABLE SKUTER CASCADE CONSTRAINTS;
DROP TABLE PRACOWNIK CASCADE CONSTRAINTS;
DROP TABLE RODZAJ_PLATNOSCI CASCADE CONSTRAINTS;
DROP TABLE WYPOZYCZENIA CASCADE CONSTRAINTS;
----------------------------------------------------------------------------------------------------------------------------------------


CREATE TABLE PANSTWO (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE WOJEWODZTWO (
    ID NUMBER(3) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL,
    ID_PANSTWO NUMBER(3) NOT NULL,
    CONSTRAINT FK_WOJEWODZTWO_PANSTWO FOREIGN KEY (ID_PANSTWO) REFERENCES PANSTWO(ID)
);

CREATE TABLE MIASTO (
    ID NUMBER(4) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL,
    ID_WOJEWODZTWO NUMBER(4) NOT NULL,
    CONSTRAINT FK_MIASTO_WOJEWODZTWO FOREIGN KEY (ID_WOJEWODZTWO) REFERENCES WOJEWODZTWO(ID)
);

CREATE TABLE ULICA (
    ID NUMBER(5) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL,
    ID_MIASTO NUMBER(5) NOT NULL,
    CONSTRAINT FK_ULICA_MIASTO FOREIGN KEY (ID_MIASTO) REFERENCES MIASTO(ID)
);

CREATE TABLE KLIENT (
    ID NUMBER(5) PRIMARY KEY,
    ID_ULICA NUMBER(5) NOT NULL,
    NR_LOKALU NUMBER(4) NOT NULL,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    DATA_URODZENIA DATE NOT NULL,
    NR_TELEFONU CHAR(9) NOT NULL,
    CONSTRAINT FK_KLIENT_ULICA FOREIGN KEY (ID_ULICA) REFERENCES ULICA(ID)
);

CREATE TABLE WYPOZYCZALNIA (
    ID NUMBER(5) PRIMARY KEY,
    ID_ULICA NUMBER(5) NOT NULL,
    NR_LOKALU NUMBER(4) NOT NULL,
    NAZWA VARCHAR2(50) NOT NULL,
    NR_TELEFONU CHAR(9) NOT NULL,
    CONSTRAINT FK_WYPOZYCZALNIA_ULICA FOREIGN KEY (ID_ULICA) REFERENCES ULICA(ID)
);

CREATE TABLE PRODUCENT (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE MODEL (
    ID NUMBER(3) PRIMARY KEY,
    ID_PRODUCENT NUMBER(2) NOT NULL,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT FK_MODEL_PRODUCENT FOREIGN KEY (ID_PRODUCENT) REFERENCES PRODUCENT(ID)
);

CREATE TABLE KOLOR (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE TYP_NAPEDU (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE PAKIET_WYPOSAZENIA (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
     -- Standardowy, Miejski, Premium, Komfortowy, Ekstremalny, Sportowy, Biznesowy, Rodzinny, Turystyczny, Luksusowy, Ekologiczny
);

CREATE TABLE SKUTER (
    ID NUMBER(6) PRIMARY KEY,
    
    ID_MODEL NUMBER(3) NOT NULL,
    ID_KOLOR NUMBER(2) NOT NULL,
    ID_TYP_NAPEDU NUMBER(2) NOT NULL,
    ID_WYPOZYCZALNIA NUMBER(5) NOT NULL,
    ID_PAKIET_WYPOSAZENIA NUMBER(2) NOT NULL,
    
    POJEMNOSC NUMBER(5,2) NOT NULL CHECK (POJEMNOSC > 0),
    ROK_PRODUKCJI NUMBER(4) NOT NULL CHECK (ROK_PRODUKCJI >= 1900),
    
    CONSTRAINT FK_SKUTER_MODEL FOREIGN KEY (ID_MODEL) REFERENCES MODEL(ID),
    CONSTRAINT FK_SKUTER_KOLOR FOREIGN KEY (ID_KOLOR) REFERENCES KOLOR(ID),
    CONSTRAINT FK_SKUTER_TYP_NAPEDU FOREIGN KEY (ID_TYP_NAPEDU) REFERENCES TYP_NAPEDU(ID),
    CONSTRAINT FK_SKUTER_WYPOZYCZALNIA FOREIGN KEY (ID_WYPOZYCZALNIA) REFERENCES WYPOZYCZALNIA(ID),
    CONSTRAINT FK_SKUTER_PAKIET_WYPOSAZENIA FOREIGN KEY (ID_PAKIET_WYPOSAZENIA) REFERENCES PAKIET_WYPOSAZENIA(ID) 
   
);

CREATE TABLE PRACOWNIK (
    ID NUMBER(5) PRIMARY KEY,
    ID_WYPOZYCZALNIA NUMBER(5) NOT NULL,
    IMIE VARCHAR2(50) NOT NULL,
    NAZWISKO VARCHAR2(50) NOT NULL,
    NR_TELEFONU CHAR(9) NOT NULL,
    CONSTRAINT FK_PRACOWNIK_WYPOZYCZALNIA FOREIGN KEY (ID_WYPOZYCZALNIA) REFERENCES WYPOZYCZALNIA(ID)
);

CREATE TABLE RODZAJ_PLATNOSCI (
    ID NUMBER(2) PRIMARY KEY,
    NAZWA VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE WYPOZYCZENIA (
    ID_KLIENT NUMBER(5) NOT NULL,
    ID_RODZAJ_PLATNOSCI NUMBER(2) NOT NULL,
    ID_SKUTER NUMBER(6) NOT NULL,
    ID_PRACOWNIK NUMBER(6) NOT NULL,
    
    CENA NUMBER(6,2) NOT NULL CHECK (CENA > 0),
    DATA_WYPOZYCZENIA TIMESTAMP NOT NULL,
    DATA_ODDANIA TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_WYPOZYCZENIA_KLIENT FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID),
    CONSTRAINT FK_WYPOZYCZENIA_R_PLATNOSCI FOREIGN KEY (ID_RODZAJ_PLATNOSCI) REFERENCES RODZAJ_PLATNOSCI(ID),
    CONSTRAINT FK_WYPOZYCZENIA_SKUTER FOREIGN KEY (ID_SKUTER) REFERENCES SKUTER(ID),
    CONSTRAINT FK_WYPOZYCZENIA_PRACOWNIK FOREIGN KEY (ID_PRACOWNIK) REFERENCES PRACOWNIK(ID)  
);



