SELECT 
    m.NAZWA AS MODEL,
    k.NAZWA AS KOLOR,
    t.NAZWA AS TYP_NAPEDU,
    COUNT(wyp.ID_SKUTER) AS LICZBA_WYPOZYCZEN,
    RANK() OVER (PARTITION BY k.NAZWA, t.NAZWA ORDER BY COUNT(wyp.ID_SKUTER) DESC) AS RANKING
FROM WYPOZYCZENIA wyp
    JOIN SKUTER s ON wyp.ID_SKUTER = s.ID
    JOIN MODEL m ON s.ID_MODEL = m.ID
    JOIN KOLOR k ON s.ID_KOLOR = k.ID
    JOIN TYP_NAPEDU t ON s.ID_TYP_NAPEDU = t.ID
GROUP BY m.NAZWA, k.NAZWA, t.NAZWA
ORDER BY k.NAZWA, t.NAZWA, RANKING;