--1. Sprawdzenie ktore modele skuterow i typy napedu sa najpopularniejsze w wypozyczalniach z rankingiem wg liczby wypozyczen

SELECT 
    wy.NAZWA AS WYPOZYCZALNIA,
    m.NAZWA AS MODEL,
    t.NAZWA AS TYP_NAPEDU,
    agg.LICZBA_WYPOZYCZEN,
    RANK() OVER (PARTITION BY agg.ID_WYPOZYCZALNIA ORDER BY agg.LICZBA_WYPOZYCZEN DESC) AS RANKING
FROM (
    SELECT 
        ID_WYPOZYCZALNIA,
        ID_MODEL,
        ID_TYP_NAPEDU,
        COUNT(*) AS LICZBA_WYPOZYCZEN
    FROM H_WYPOZYCZENIA
    GROUP BY ID_WYPOZYCZALNIA, ID_MODEL, ID_TYP_NAPEDU
) agg
JOIN H_WYPOZYCZALNIA wy ON agg.ID_WYPOZYCZALNIA = wy.ID
JOIN H_MODEL m ON agg.ID_MODEL = m.ID
JOIN H_TYP_NAPEDU t ON agg.ID_TYP_NAPEDU = t.ID
ORDER BY wy.NAZWA, RANKING;

-- Sprawdzenie sredniej pojemnosci skuterow wg producenta, typu napedu i pakietu w hurtowni

SELECT 
    p.NAZWA AS PRODUCENT,
    tn.NAZWA AS TYP_NAPEDU,
    pw.NAZWA AS PAKIET_WYPOSAZENIA,
    agg.SREDNIA_POJEMNOSC,
    DENSE_RANK() OVER (ORDER BY agg.SREDNIA_POJEMNOSC DESC) AS RANKING
FROM (
    SELECT 
        w.ID_PRODUCENT,
        w.ID_TYP_NAPEDU,
        w.ID_PAKIET_WYPOSAZENIA,
        AVG(w.POJEMNOSC) AS SREDNIA_POJEMNOSC
    FROM H_WYPOZYCZENIA w
    GROUP BY w.ID_PRODUCENT, w.ID_TYP_NAPEDU, w.ID_PAKIET_WYPOSAZENIA
) agg
JOIN H_PRODUCENT p ON agg.ID_PRODUCENT = p.ID
JOIN H_TYP_NAPEDU tn ON agg.ID_TYP_NAPEDU = tn.ID
JOIN H_PAKIET_WYPOSAZENIA pw ON agg.ID_PAKIET_WYPOSAZENIA = pw.ID
ORDER BY RANKING;
