SELECT
    NVL(m.NAZWA, 'RAZEM - MODEL') AS MODEL,
    NVL(k.NAZWA, 'RAZEM - KOLOR') AS KOLOR,
    NVL(p.IMIE, 'RAZEM -') || ' ' || NVL(p.NAZWISKO, 'PRACOWNIK') AS PRACOWNIK,
    agg.LICZBA_WYPOZYCZEN AS LICZBA_WYPOZYCZEN
FROM (
    SELECT
        w.ID_MODEL AS MODEL_ID,
        w.ID_KOLOR AS KOLOR_ID,
        w.ID_PRACOWNIK AS PRACOWNIK_ID,
        COUNT(*) AS LICZBA_WYPOZYCZEN
    FROM H_WYPOZYCZENIA w
    GROUP BY CUBE(w.ID_MODEL, w.ID_KOLOR, w.ID_PRACOWNIK)
) agg
LEFT JOIN H_MODEL m ON agg.MODEL_ID = m.ID
LEFT JOIN H_KOLOR k ON agg.KOLOR_ID = k.ID
LEFT JOIN H_PRACOWNIK p ON agg.PRACOWNIK_ID = p.ID
ORDER BY LICZBA_WYPOZYCZEN;
