SPOOL wynik.txt

SELECT 
    P.NAZWA AS PANSTWO,
    WY.NAZWA AS WYPOZYCZALNIA,
    PR.NAZWA AS PRODUCENT,
    S.ROK_PRODUKCJI,

    MIN(S.ROK_PRODUKCJI) OVER (PARTITION BY P.ID, WY.ID, PR.ID) AS NAJSTARSZY_ROK,
    MAX(S.ROK_PRODUKCJI) OVER (PARTITION BY P.ID, WY.ID, PR.ID) AS NAJNOWSZY_ROK

FROM 
    WYPOZYCZENIA W
JOIN SKUTER S ON W.ID_SKUTER = S.ID
JOIN MODEL M ON S.ID_MODEL = M.ID
JOIN PRODUCENT PR ON M.ID_PRODUCENT = PR.ID
JOIN WYPOZYCZALNIA WY ON S.ID_WYPOZYCZALNIA = WY.ID
JOIN ULICA U ON WY.ID_ULICA = U.ID
JOIN MIASTO MIA ON U.ID_MIASTO = MIA.ID
JOIN WOJEWODZTWO WOJ ON MIA.ID_WOJEWODZTWO = WOJ.ID
JOIN PANSTWO P ON WOJ.ID_PANSTWO = P.ID;

spool off
