SELECT 
    agg.MIESIAC,
    wypozyczalnia.NAZWA AS NAZWA_WYPOZYCZALNI,
    producent.NAZWA AS NAZWA_PRODUCENTA,
    agg.LICZBA_WYPOZYCZEN,
    round(AVG(agg.LICZBA_WYPOZYCZEN) OVER (PARTITION BY wypozyczalnia.NAZWA, producent.NAZWA ORDER BY agg.MIESIAC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2) AS SREDNIA_LICZBA_WYPOZYCZEN
FROM (
    SELECT 
        TO_CHAR(wyp.DATA_WYPOZYCZENIA, 'YYYY-MM') AS MIESIAC,
        p.ID_WYPOZYCZALNIA,
        m.ID_PRODUCENT,
        COUNT(*) AS LICZBA_WYPOZYCZEN
    FROM WYPOZYCZENIA wyp
    JOIN SKUTER s ON wyp.ID_SKUTER = s.ID
    JOIN MODEL m ON s.ID_MODEL = m.ID
    JOIN PRACOWNIK p ON wyp.ID_PRACOWNIK = p.ID
    GROUP BY TO_CHAR(wyp.DATA_WYPOZYCZENIA, 'YYYY-MM'), p.ID_WYPOZYCZALNIA, m.ID_PRODUCENT
) agg
JOIN WYPOZYCZALNIA wypozyczalnia ON agg.ID_WYPOZYCZALNIA = wypozyczalnia.ID
JOIN PRODUCENT producent ON agg.ID_PRODUCENT = producent.ID
ORDER BY agg.MIESIAC, wypozyczalnia.NAZWA, producent.NAZWA;


