SELECT
    NVL(m.NAZWA, 'RAZEM - MODEL') AS MODEL,
    NVL(k.NAZWA, 'RAZEM - KOLOR') AS KOLOR,
    NVL(p.IMIE, 'RAZEM -') || ' ' || NVL(p.NAZWISKO, 'PRACOWNIK') AS PRACOWNIK,
    agg.LICZBA_WYPOZYCZEN 
FROM (
    SELECT
        m.ID AS MODEL_ID,
        k.ID AS KOLOR_ID,
        p.ID AS PRACOWNIK_ID,
        COUNT(w.ID) AS LICZBA_WYPOZYCZEN
    FROM WYPOZYCZENIA w
        JOIN SKUTER s ON w.ID_SKUTER = s.ID
        JOIN MODEL m ON s.ID_MODEL = m.ID
        JOIN KOLOR k ON s.ID_KOLOR = k.ID
        JOIN PRACOWNIK p ON w.ID_PRACOWNIK = p.ID
    GROUP BY CUBE(m.ID, k.ID, p.ID)
) agg
LEFT JOIN MODEL m ON agg.MODEL_ID = m.ID
LEFT JOIN KOLOR k ON agg.KOLOR_ID = k.ID
LEFT JOIN PRACOWNIK p ON agg.PRACOWNIK_ID = p.ID
ORDER BY LICZBA_WYPOZYCZEN;