-- Analiza liczby wypo�ycze� skuter�w i �redniej liczby wypo�ycze� w poszczeg�lnych latach dla r�nych producent�w i metod p�atno�ci.

SPOOL wynik1.txt

SELECT 
    p.NAZWA AS PRODUCENT,
    rp.NAZWA AS RODZAJ_PLATNOSCI,
    EXTRACT(YEAR FROM w.DATA_WYPOZYCZENIA) AS ROK,
    COUNT(w.ID_SKUTER) AS LICZBA_WYPOZYCZEN,
    AVG(COUNT(w.ID_SKUTER)) OVER (PARTITION BY p.NAZWA, EXTRACT(YEAR FROM w.DATA_WYPOZYCZENIA)) AS SREDNIA_WYPOZYCZEN
FROM WYPOZYCZENIA w
    JOIN SKUTER s ON w.ID_SKUTER = s.ID
    JOIN MODEL m ON s.ID_MODEL = m.ID
    JOIN PRODUCENT p ON m.ID_PRODUCENT = p.ID
    JOIN RODZAJ_PLATNOSCI rp ON w.ID_RODZAJ_PLATNOSCI = rp.ID
GROUP BY p.NAZWA, rp.NAZWA, EXTRACT(YEAR FROM w.DATA_WYPOZYCZENIA)
ORDER BY ROK, p.NAZWA, rp.NAZWA;

SPOOL OFF;
