-- Analiza liczby wypo¿yczeñ skuterów i œredniej liczby wypo¿yczeñ w poszczególnych latach dla ró¿nych producentów i metod p³atnoœci.

SELECT 
    p.NAZWA AS PRODUCENT,
    rp.NAZWA AS RODZAJ_PLATNOSCI,
    EXTRACT(YEAR FROM w.DATA_WYPOZYCZENIA) AS ROK,
    COUNT(w.ID_SKUTER) AS LICZBA_WYPOZYCZEN,
    AVG(COUNT(w.ID_SKUTER)) OVER (PARTITION BY p.NAZWA, EXTRACT(YEAR FROM w.DATA_WYPOZYCZENIA)) AS SREDNIA_WYPOZYCZEN
FROM WYPOZYCZENIA w
    JOIN SKUTER s ON w.ID_SKUTER = s.ID
    JOIN MODEL m ON s.ID_MODEL = m.ID
    JOIN PRODUCENT p ON m.ID_PRODUCENT = p.ID
    JOIN RODZAJ_PLATNOSCI rp ON w.ID_RODZAJ_PLATNOSCI = rp.ID
GROUP BY p.NAZWA, rp.NAZWA, EXTRACT(YEAR FROM w.DATA_WYPOZYCZENIA)
ORDER BY ROK, p.NAZWA, rp.NAZWA;


