
-- Liczba klientow roczno-miesiecznie wg producenta i typu napedu
SELECT 
    agg.ROK_WYPOZYCZENIA,
    m.NAZWA AS NAZWA_MIESIACA,
    p.NAZWA AS NAZWA_PRODUCENTA,
    tn.NAZWA AS NAZWA_TYPU_NAPEDU,
    agg.LICZBA_KLIENTOW,
    SUM(agg.LICZBA_KLIENTOW) OVER (PARTITION BY p.NAZWA ORDER BY agg.ROK_WYPOZYCZENIA, m.ID) AS SUMA_NARASTAJACO
FROM (
    SELECT 
        ROK_WYPOZYCZENIA,
        ID_MIESIAC_WYPOZYCZENIA,
        ID_PRODUCENT,
        ID_TYP_NAPEDU,
        COUNT(DISTINCT ID_KLIENT) AS LICZBA_KLIENTOW
    FROM H_WYPOZYCZENIA
    GROUP BY ROK_WYPOZYCZENIA, ID_MIESIAC_WYPOZYCZENIA, ID_PRODUCENT, ID_TYP_NAPEDU
) agg
JOIN H_MIESIAC m ON agg.ID_MIESIAC_WYPOZYCZENIA = m.ID
JOIN H_PRODUCENT p ON agg.ID_PRODUCENT = p.ID
JOIN H_TYP_NAPEDU tn ON agg.ID_TYP_NAPEDU = tn.ID
ORDER BY p.NAZWA, agg.ROK_WYPOZYCZENIA, m.ID;

--Sprawdzenie, jak zmienia siê srednia roczna liczba wypozyczeñ skuterow poszczegolnych producentow w zaleznosci od rodzaju platnosci.
SELECT 
    producent.NAZWA AS NAZWA_PRODUCENTA,
    platnosc.NAZWA AS NAZWA_RODZAJU_PLATNOSCI,
    agg.ROK,
    agg.LICZBA_WYPOZYCZEN,
    AVG(agg.LICZBA_WYPOZYCZEN) OVER (
        PARTITION BY producent.NAZWA, agg.ROK
    ) AS SREDNIA_ROCZNA_DLA_PRODUCENTA
FROM (
    SELECT 
        ROK_WYPOZYCZENIA AS ROK,
        ID_PRODUCENT,
        ID_RODZAJ_PLATNOSCI,
        COUNT(*) AS LICZBA_WYPOZYCZEN
    FROM H_WYPOZYCZENIA
    GROUP BY ROK_WYPOZYCZENIA, ID_PRODUCENT, ID_RODZAJ_PLATNOSCI
) agg
JOIN H_PRODUCENT producent ON agg.ID_PRODUCENT = producent.ID
JOIN H_RODZAJ_PLATNOSCI platnosc ON agg.ID_RODZAJ_PLATNOSCI = platnosc.ID
ORDER BY agg.ROK, NAZWA_PRODUCENTA, NAZWA_RODZAJU_PLATNOSCI;
