-- 1. Liczba unikalnych klientow w podziale na miesiac i rok, wedlug producenta skutera, typu napedu oraz rodzaju platnosci

SELECT 
    AGG.ROK_WYPOZYCZENIA,
    miesiac.NAZWA AS NAZWA_MIESIACA,
    producent.NAZWA AS NAZWA_PRODUCENTA,
    typ_nap.NAZWA AS NAZWA_TYPU_NAPEDU,
    r_platnosci.NAZWA AS NAZWA_RODZAJU_PLATNOSCI,
    AGG.LICZBA_KLIENTOW,
    SUM(AGG.LICZBA_KLIENTOW) OVER (
        PARTITION BY producent.ID, typ_nap.ID, r_platnosci.ID
        ORDER BY AGG.ROK_WYPOZYCZENIA, miesiac.ID
    ) AS SUMA_NARASTAJACO
FROM (
    SELECT
        ROK_WYPOZYCZENIA,
        ID_MIESIAC_WYPOZYCZENIA,
        ID_PRODUCENT,
        ID_TYP_NAPEDU,
        ID_RODZAJ_PLATNOSCI,
        COUNT(DISTINCT ID_KLIENT) AS LICZBA_KLIENTOW
    FROM H_WYPOZYCZENIA
    GROUP BY
        ROK_WYPOZYCZENIA,
        ID_MIESIAC_WYPOZYCZENIA,
        ID_PRODUCENT,
        ID_TYP_NAPEDU,
        ID_RODZAJ_PLATNOSCI
) AGG
JOIN H_MIESIAC miesiac ON AGG.ID_MIESIAC_WYPOZYCZENIA = miesiac.ID
JOIN H_PRODUCENT producent ON AGG.ID_PRODUCENT = producent.ID
JOIN H_TYP_NAPEDU typ_nap ON AGG.ID_TYP_NAPEDU = typ_nap.ID
JOIN H_RODZAJ_PLATNOSCI r_platnosci ON AGG.ID_RODZAJ_PLATNOSCI = r_platnosci.ID;

-- 2. Liczba wypozyczen miesiecznie z podzialem na panstwo, wypozyczalnie oraz producentow wraz ze srednia liczba wypozyczen narastajaco
SELECT
    agg.ROK_WYPOZYCZENIA,
    m.NAZWA AS NAZWA_MIESIACA,
    p.NAZWA AS NAZWA_PANSTWA,
    w.NAZWA AS NAZWA_WYPOZYCZALNI,
    pr.NAZWA AS NAZWA_PRODUCENTA,
    agg.LICZBA_WYPOZYCZEN,
    ROUND(
        AVG(agg.LICZBA_WYPOZYCZEN) OVER (
            PARTITION BY agg.ID_PANSTWO, agg.ID_WYPOZYCZALNIA, agg.ID_PRODUCENT
            ORDER BY agg.ROK_WYPOZYCZENIA, agg.ID_MIESIAC_WYPOZYCZENIA
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ), 2
    ) AS SREDNIA_LICZBA_WYPOZYCZEN
FROM (
    SELECT 
        ROK_WYPOZYCZENIA,
        ID_MIESIAC_WYPOZYCZENIA,
        ID_WYPOZYCZALNIA_PRACOWNIK AS ID_WYPOZYCZALNIA,
        ID_PRODUCENT,
        ID_PANSTWO_PRACOWNIK AS ID_PANSTWO,
        COUNT(*) AS LICZBA_WYPOZYCZEN
    FROM H_WYPOZYCZENIA
    GROUP BY 
        ROK_WYPOZYCZENIA,
        ID_MIESIAC_WYPOZYCZENIA,
        ID_WYPOZYCZALNIA_PRACOWNIK,
        ID_PRODUCENT,
        ID_PANSTWO_PRACOWNIK
) agg
JOIN H_MIESIAC m ON agg.ID_MIESIAC_WYPOZYCZENIA = m.ID
JOIN H_WYPOZYCZALNIA w ON agg.ID_WYPOZYCZALNIA = w.ID
JOIN H_PRODUCENT pr ON agg.ID_PRODUCENT = pr.ID
JOIN H_PANSTWO p ON agg.ID_PANSTWO = p.ID;

-- 3. Liczba wypozyczen miesiecznie z podzialem na panstwo, wypozyczalnie oraz rodzaj platnosci wraz z minimalna, srednia i maksymalna cena wypozyczenia
SELECT
    agg.ROK_WYPOZYCZENIA,
    m.NAZWA AS NAZWA_MIESIACA,
    p.NAZWA AS NAZWA_PANSTWA,
    w.NAZWA AS NAZWA_WYPOZYCZALNI,
    r.NAZWA AS NAZWA_RODZAJU_PLATNOSCI,
    agg.LICZBA_WYPOZYCZEN,
    ROUND(agg.MIN_CENA, 2) AS MIN_CENA,
    ROUND(agg.SREDNIA_CENA, 2) AS SREDNIA_CENA,
    ROUND(agg.MAX_CENA, 2) AS MAX_CENA
FROM (
    SELECT
        ROK_WYPOZYCZENIA,
        ID_MIESIAC_WYPOZYCZENIA,
        ID_WYPOZYCZALNIA_PRACOWNIK AS ID_WYPOZYCZALNIA,
        ID_PANSTWO_PRACOWNIK AS ID_PANSTWO,
        ID_RODZAJ_PLATNOSCI,
        COUNT(*) AS LICZBA_WYPOZYCZEN,
        MIN(CENA) AS MIN_CENA,
        AVG(CENA) AS SREDNIA_CENA,
        MAX(CENA) AS MAX_CENA
    FROM H_WYPOZYCZENIA
    GROUP BY
        ROK_WYPOZYCZENIA,
        ID_MIESIAC_WYPOZYCZENIA,
        ID_WYPOZYCZALNIA_PRACOWNIK,
        ID_PANSTWO_PRACOWNIK,
        ID_RODZAJ_PLATNOSCI
) agg
JOIN H_MIESIAC m ON agg.ID_MIESIAC_WYPOZYCZENIA = m.ID
JOIN H_WYPOZYCZALNIA w ON agg.ID_WYPOZYCZALNIA = w.ID
JOIN H_PANSTWO p ON agg.ID_PANSTWO = p.ID
JOIN H_RODZAJ_PLATNOSCI r ON agg.ID_RODZAJ_PLATNOSCI = r.ID
ORDER BY agg.ROK_WYPOZYCZENIA, agg.ID_MIESIAC_WYPOZYCZENIA, p.NAZWA, w.NAZWA, r.NAZWA
