SELECT 'PANSTWO' AS table_name, COUNT(*) AS record_count FROM PANSTWO
UNION ALL
SELECT 'WOJEWODZTWO', COUNT(*) FROM WOJEWODZTWO
UNION ALL
SELECT 'MIASTO', COUNT(*) FROM MIASTO
UNION ALL
SELECT 'ULICA', COUNT(*) FROM ULICA
UNION ALL
SELECT 'KLIENT', COUNT(*) FROM KLIENT
UNION ALL
SELECT 'WYPOZYCZALNIA', COUNT(*) FROM WYPOZYCZALNIA
UNION ALL
SELECT 'PRODUCENT', COUNT(*) FROM PRODUCENT
UNION ALL
SELECT 'MODEL', COUNT(*) FROM MODEL
UNION ALL
SELECT 'KOLOR', COUNT(*) FROM KOLOR
UNION ALL
SELECT 'TYP_NAPEDU', COUNT(*) FROM TYP_NAPEDU
UNION ALL
SELECT 'PAKIET_WYPOSAZENIA', COUNT(*) FROM PAKIET_WYPOSAZENIA
UNION ALL
SELECT 'SKUTER', COUNT(*) FROM SKUTER
UNION ALL
SELECT 'PRACOWNIK', COUNT(*) FROM PRACOWNIK
UNION ALL
SELECT 'RODZAJ_PLATNOSCI', COUNT(*) FROM RODZAJ_PLATNOSCI
UNION ALL
SELECT 'WYPOZYCZENIA', COUNT(*) FROM WYPOZYCZENIA;
