-- PARTYCJE OBLICZENIOWE

-- 1. Srednia cena wypozyczenia wg producenta, typu napedu, pakietu i modelu


SELECT 
    PR.NAZWA AS PRODUCENT,
    M.NAZWA AS MODEL,
    TN.NAZWA AS TYP_NAPEDU,
    PW.NAZWA AS PAKIET,
    W.CENA,
    AVG(W.CENA) OVER (PARTITION BY PR.ID, M.ID, TN.ID, PW.ID) AS SREDNIA_CENA

FROM 
    WYPOZYCZENIA W
JOIN SKUTER S ON W.ID_SKUTER = S.ID
JOIN MODEL M ON S.ID_MODEL = M.ID
JOIN PRODUCENT PR ON M.ID_PRODUCENT = PR.ID
JOIN TYP_NAPEDU TN ON S.ID_TYP_NAPEDU = TN.ID
JOIN PAKIET_WYPOSAZENIA PW ON S.ID_PAKIET_WYPOSAZENIA = PW.ID;


--------------------------------------------------------------------------------------------
-- 2. Srednia cena wypozyczenia wg klienta, rodzaju platnosci i koloru skutera


SELECT 
    K.IMIE || ' ' || K.NAZWISKO AS KLIENT,
    RP.NAZWA AS PLATNOSC,
    KOL.NAZWA AS KOLOR,
    W.CENA,

    round(AVG(W.CENA) OVER (PARTITION BY K.ID, RP.ID, KOL.ID), 2) AS SREDNIA_CENA

FROM 
    WYPOZYCZENIA W
JOIN KLIENT K ON W.ID_KLIENT = K.ID
JOIN SKUTER S ON W.ID_SKUTER = S.ID
JOIN KOLOR KOL ON S.ID_KOLOR = KOL.ID
JOIN RODZAJ_PLATNOSCI RP ON W.ID_RODZAJ_PLATNOSCI = RP.ID;


--------------------------------------------------------------------------------------------
-- 3. Najstarsze i najnowszee skutery od danego producenta, ktore sa uzywane w konkretnym miescie i wypozyczalni

SELECT 
    M.NAZWA AS MIASTO,
    WY.NAZWA AS WYPOZYCZALNIA,
    PR.NAZWA AS PRODUCENT,
    S.ROK_PRODUKCJI,

    MIN(S.ROK_PRODUKCJI) OVER (PARTITION BY M.ID, WY.ID, PR.ID) AS NAJSTARSZY_ROK,
    MAX(S.ROK_PRODUKCJI) OVER (PARTITION BY M.ID, WY.ID, PR.ID) AS NAJNOWSZY_ROK

FROM 
    WYPOZYCZENIA W
JOIN SKUTER S ON W.ID_SKUTER = S.ID
JOIN MODEL MO ON S.ID_MODEL = MO.ID
JOIN PRODUCENT PR ON MO.ID_PRODUCENT = PR.ID
JOIN WYPOZYCZALNIA WY ON S.ID_WYPOZYCZALNIA = WY.ID
JOIN ULICA U ON WY.ID_ULICA = U.ID
JOIN MIASTO M ON U.ID_MIASTO = M.ID;

