-- Srednia cena wypozyczenia wg producenta, typu napedu, pakietu i modelu
SELECT 
    PR.NAZWA AS PRODUCENT,
    M.NAZWA AS MODEL,
    TN.NAZWA AS TYP_NAPEDU,
    PW.NAZWA AS PAKIET,
    W.CENA,
    AVG(W.CENA) OVER (PARTITION BY PR.ID, M.ID, TN.ID, PW.ID) AS SREDNIA_CENA
FROM 
    H_WYPOZYCZENIA W
JOIN H_PRODUCENT PR ON W.ID_PRODUCENT = PR.ID
JOIN H_MODEL M ON W.ID_MODEL = M.ID
JOIN H_TYP_NAPEDU TN ON W.ID_TYP_NAPEDU = TN.ID
JOIN H_PAKIET_WYPOSAZENIA PW ON W.ID_PAKIET_WYPOSAZENIA = PW.ID;

-- Srednia cena wypozyczenia wg klienta, rodzaju platnosci i koloru skutera
SELECT 
    K.IMIE || ' ' || K.NAZWISKO AS KLIENT,
    RP.NAZWA AS PLATNOSC,
    KOL.NAZWA AS KOLOR,
    W.CENA,

    ROUND(AVG(W.CENA) OVER (PARTITION BY K.ID, RP.ID, KOL.ID), 2) AS SREDNIA_CENA

FROM 
    H_WYPOZYCZENIA W
JOIN H_KLIENT K ON W.ID_KLIENT = K.ID
JOIN H_KOLOR KOL ON W.ID_KOLOR = KOL.ID
JOIN H_RODZAJ_PLATNOSCI RP ON W.ID_RODZAJ_PLATNOSCI = RP.ID;

-- Najstarsze i najnowszee skutery od danego producenta, ktore sa uzywane w konkretnym miescie i wypozyczalni
SELECT 
    M.NAZWA AS MIASTO,
    WY.NAZWA AS WYPOZYCZALNIA,
    PR.NAZWA AS PRODUCENT,
    W.ROK_PRODUKCJI,

    MIN(W.ROK_PRODUKCJI) OVER (PARTITION BY M.ID, WY.ID, PR.ID) AS NAJSTARSZY_ROK,
    MAX(W.ROK_PRODUKCJI) OVER (PARTITION BY M.ID, WY.ID, PR.ID) AS NAJNOWSZY_ROK

FROM 
    H_WYPOZYCZENIA W
JOIN H_WYPOZYCZALNIA WY ON W.ID_WYPOZYCZALNIA = WY.ID
JOIN H_MIASTO M ON W.ID_MIASTO_WYPOZYCZENIA = M.ID
JOIN H_PRODUCENT PR ON W.ID_PRODUCENT = PR.ID;