-- PARTYCJE OBLICZENIOWE

-- 1. Srednia cena wypozyczenia wg producenta, typu napedu, pakietu i modelu

SELECT
    pr.NAZWA AS PRODUCENT,
    m.NAZWA AS MODEL,
    tn.NAZWA AS TYP_NAPEDU,
    pw.NAZWA AS PAKIET,
    agg.CENA,
    agg.SREDNIA_CENA
FROM (
    SELECT
        ID_PRODUCENT,
        ID_MODEL,
        ID_TYP_NAPEDU,
        ID_PAKIET_WYPOSAZENIA,
        CENA,
        ROUND(AVG(CENA) OVER (PARTITION BY ID_PRODUCENT, ID_MODEL, ID_TYP_NAPEDU, ID_PAKIET_WYPOSAZENIA), 2) AS SREDNIA_CENA
    FROM H_WYPOZYCZENIA
) agg
JOIN H_PRODUCENT pr ON agg.ID_PRODUCENT = pr.ID
JOIN H_MODEL m ON agg.ID_MODEL = m.ID
JOIN H_TYP_NAPEDU tn ON agg.ID_TYP_NAPEDU = tn.ID
JOIN H_PAKIET_WYPOSAZENIA pw ON agg.ID_PAKIET_WYPOSAZENIA = pw.ID;


-- 2. Srednia cena wypozyczenia wg klienta, rodzaju platnosci i koloru skutera
SELECT
    k.IMIE || ' ' || k.NAZWISKO AS KLIENT,
    rp.NAZWA AS PLATNOSC,
    kol.NAZWA AS KOLOR,
    agg.CENA,
    agg.SREDNIA_CENA
FROM (
    SELECT
        ID_KLIENT,
        ID_RODZAJ_PLATNOSCI,
        ID_KOLOR,
        CENA,
        ROUND(AVG(CENA) OVER (PARTITION BY ID_KLIENT, ID_RODZAJ_PLATNOSCI, ID_KOLOR), 2) AS SREDNIA_CENA
    FROM H_WYPOZYCZENIA
) agg
JOIN H_KLIENT k ON agg.ID_KLIENT = k.ID
JOIN H_RODZAJ_PLATNOSCI rp ON agg.ID_RODZAJ_PLATNOSCI = rp.ID
JOIN H_KOLOR kol ON agg.ID_KOLOR = kol.ID;


-- 3. Najstarsze i najnowszee skutery od danego producenta, ktore sa uzywane w konkretnym miescie i wypozyczalni
SELECT
    m.NAZWA AS MIASTO,
    wy.NAZWA AS WYPOZYCZALNIA,
    pr.NAZWA AS PRODUCENT,
    agg.ROK_PRODUKCJI,
    agg.NAJSTARSZY_ROK,
    agg.NAJNOWSZY_ROK
FROM (
    SELECT 
        ID_MIASTO_SKUTER,
        ID_WYPOZYCZALNIA_SKUTER,
        ID_PRODUCENT,
        ROK_PRODUKCJI,
        MIN(ROK_PRODUKCJI) OVER (PARTITION BY ID_MIASTO_SKUTER, ID_WYPOZYCZALNIA_SKUTER, ID_PRODUCENT) AS NAJSTARSZY_ROK,
        MAX(ROK_PRODUKCJI) OVER (PARTITION BY ID_MIASTO_SKUTER, ID_WYPOZYCZALNIA_SKUTER, ID_PRODUCENT) AS NAJNOWSZY_ROK
    FROM H_WYPOZYCZENIA
) agg
JOIN H_MIASTO m ON agg.ID_MIASTO_SKUTER = m.ID
JOIN H_WYPOZYCZALNIA wy ON agg.ID_WYPOZYCZALNIA_SKUTER = wy.ID
JOIN H_PRODUCENT pr ON agg.ID_PRODUCENT = pr.ID;
