SELECT COUNT(*) FROM (
    SELECT 
    NVL(pr.NAZWA, 'RAZEM - PRODUCENT') AS PRODUCENT,
    NVL(m.NAZWA, 'RAZEM - MODEL') AS MODEL,
    NVL(k.NAZWA, 'RAZEM - KOLOR') AS KOLOR,
    NVL(tn.NAZWA, 'RAZEM - TYP NAPEDU') AS TYP_NAPEDU,
    agg.LACZNY_PRZYCHOD
FROM (
    SELECT 
        DISTINCT
        f.ID_PRODUCENT AS PRODUCENT_ID,
        f.ID_MODEL AS MODEL_ID,
        f.ID_KOLOR AS KOLOR_ID,
        f.ID_TYP_NAPEDU AS TYP_NAPEDU_ID,
        SUM(f.CENA) AS LACZNY_PRZYCHOD
    FROM H_WYPOZYCZENIA f
    GROUP BY CUBE (f.ID_PRODUCENT, f.ID_MODEL, f.ID_KOLOR, f.ID_TYP_NAPEDU)
) agg
LEFT JOIN H_PRODUCENT pr ON agg.PRODUCENT_ID = pr.ID
LEFT JOIN H_MODEL m ON agg.MODEL_ID = m.ID
LEFT JOIN H_KOLOR k ON agg.KOLOR_ID = k.ID
LEFT JOIN H_TYP_NAPEDU tn ON agg.TYP_NAPEDU_ID = tn.ID
ORDER BY agg.LACZNY_PRZYCHOD
);



SELECT COUNT(*) FROM (
    SELECT
    NVL(m.NAZWA, 'RAZEM - MODEL') AS MODEL,
    NVL(k.NAZWA, 'RAZEM - KOLOR') AS KOLOR,
    NVL(p.IMIE, 'RAZEM -') || ' ' || NVL(p.NAZWISKO, 'PRACOWNIK') AS PRACOWNIK,
    agg.LICZBA_WYPOZYCZEN AS LICZBA_WYPOZYCZEN
FROM (
    SELECT
        w.ID_MODEL AS MODEL_ID,
        w.ID_KOLOR AS KOLOR_ID,
        w.ID_PRACOWNIK AS PRACOWNIK_ID,
        COUNT(*) AS LICZBA_WYPOZYCZEN
    FROM H_WYPOZYCZENIA w
    GROUP BY CUBE(w.ID_MODEL, w.ID_KOLOR, w.ID_PRACOWNIK)
) agg
LEFT JOIN H_MODEL m ON agg.MODEL_ID = m.ID
LEFT JOIN H_KOLOR k ON agg.KOLOR_ID = k.ID
LEFT JOIN H_PRACOWNIK p ON agg.PRACOWNIK_ID = p.ID
ORDER BY LICZBA_WYPOZYCZEN
);



SELECT COUNT(*) FROM (
    SELECT 
    NVL(w.NAZWA, 'RAZEM - WOJEWODZTWO') AS WOJEWODZTWO,
    NVL(m.NAZWA, 'RAZEM - MIASTO') AS MIASTO,
    NVL(wy.NAZWA, 'RAZEM - WYPOZYCZALNIA') AS WYPOZYCZALNIA,
    agg.LICZBA_KLIENTOW
FROM (
    SELECT 
        f.ID_WOJEWODZTWO_KLIENT AS WOJEWODZTWO_ID,
        f.ID_MIASTO_KLIENT AS MIASTO_ID,
        f.ID_WYPOZYCZALNIA_PRACOWNIK AS WYPOZYCZALNIA_ID,
        COUNT(*) AS LICZBA_KLIENTOW
    FROM H_WYPOZYCZENIA f
    GROUP BY CUBE (f.ID_WOJEWODZTWO_KLIENT, f.ID_MIASTO_KLIENT, f.ID_WYPOZYCZALNIA_PRACOWNIK)
) agg
LEFT JOIN H_WOJEWODZTWO w ON agg.WOJEWODZTWO_ID = w.ID
LEFT JOIN H_MIASTO m ON agg.MIASTO_ID = m.ID
LEFT JOIN H_WYPOZYCZALNIA wy ON agg.WYPOZYCZALNIA_ID = wy.ID
ORDER BY agg.LICZBA_KLIENTOW
);

