SELECT COUNT(*) FROM (
    SELECT 
    pr.NAZWA AS PRODUCENT,
    m.NAZWA AS MODEL,
    tn.NAZWA AS TYP_NAPEDU,
    pw.NAZWA AS PAKIET,
    agg.CENA,
    agg.SREDNIA_CENA
FROM (
    SELECT 
        pr.ID AS ID_PRODUCENT,
        mo.ID AS ID_MODEL,
        tn.ID AS ID_TYP_NAPEDU,
        pw.ID AS ID_PAKIET,
        w.CENA,
        ROUND(
            AVG(w.CENA) OVER (
                PARTITION BY pr.ID, mo.ID, tn.ID, pw.ID
            ), 2
        ) AS SREDNIA_CENA
    FROM WYPOZYCZENIA w
    JOIN SKUTER s ON w.ID_SKUTER = s.ID
    JOIN MODEL mo ON s.ID_MODEL = mo.ID
    JOIN PRODUCENT pr ON mo.ID_PRODUCENT = pr.ID
    JOIN TYP_NAPEDU tn ON s.ID_TYP_NAPEDU = tn.ID
    JOIN PAKIET_WYPOSAZENIA pw ON s.ID_PAKIET_WYPOSAZENIA = pw.ID
) agg
JOIN PRODUCENT pr ON agg.ID_PRODUCENT = pr.ID
JOIN MODEL m ON agg.ID_MODEL = m.ID
JOIN TYP_NAPEDU tn ON agg.ID_TYP_NAPEDU = tn.ID
JOIN PAKIET_WYPOSAZENIA pw ON agg.ID_PAKIET = pw.ID
);



SELECT COUNT(*) FROM (
    SELECT 
    k.IMIE || ' ' || k.NAZWISKO AS KLIENT,
    rp.NAZWA AS PLATNOSC,
    kol.NAZWA AS KOLOR,
    agg.CENA,
    agg.SREDNIA_CENA
FROM (
    SELECT 
        w.ID_KLIENT,
        w.ID_RODZAJ_PLATNOSCI,
        s.ID_KOLOR,
        w.CENA,
        ROUND(AVG(w.CENA) OVER (PARTITION BY w.ID_KLIENT, w.ID_RODZAJ_PLATNOSCI, s.ID_KOLOR), 2) AS SREDNIA_CENA
    FROM WYPOZYCZENIA w
    JOIN SKUTER s ON w.ID_SKUTER = s.ID
) agg
JOIN KLIENT k ON agg.ID_KLIENT = k.ID
JOIN RODZAJ_PLATNOSCI rp ON agg.ID_RODZAJ_PLATNOSCI = rp.ID
JOIN KOLOR kol ON agg.ID_KOLOR = kol.ID
);

SELECT COUNT(*) FROM (
    SELECT
    m.NAZWA AS MIASTO,
    wy.NAZWA AS WYPOZYCZALNIA,
    pr.NAZWA AS PRODUCENT,
    agg.ROK_PRODUKCJI,
    agg.NAJSTARSZY_ROK,
    agg.NAJNOWSZY_ROK
FROM (
    SELECT 
        s.ROK_PRODUKCJI,
        wy.ID AS ID_WYPOZYCZALNIA,
        m.ID AS ID_MIASTO,
        pr.ID AS ID_PRODUCENT,
        MIN(s.ROK_PRODUKCJI) OVER (PARTITION BY m.ID, wy.ID, pr.ID) AS NAJSTARSZY_ROK,
        MAX(s.ROK_PRODUKCJI) OVER (PARTITION BY m.ID, wy.ID, pr.ID) AS NAJNOWSZY_ROK
    FROM WYPOZYCZENIA w
    JOIN SKUTER s ON w.ID_SKUTER = s.ID
    JOIN MODEL mo ON s.ID_MODEL = mo.ID
    JOIN PRODUCENT pr ON mo.ID_PRODUCENT = pr.ID
    JOIN WYPOZYCZALNIA wy ON s.ID_WYPOZYCZALNIA = wy.ID
    JOIN ULICA u ON wy.ID_ULICA = u.ID
    JOIN MIASTO m ON u.ID_MIASTO = m.ID
) agg
JOIN MIASTO m ON agg.ID_MIASTO = m.ID
JOIN WYPOZYCZALNIA wy ON agg.ID_WYPOZYCZALNIA = wy.ID
JOIN PRODUCENT pr ON agg.ID_PRODUCENT = pr.ID
);

