LOAD DATA
INFILE 'csv/wypozyczenia.csv'
REPLACE
INTO TABLE WYPOZYCZENIA
FIELDS TERMINATED BY '|'
(ID_KLIENT, ID_RODZAJ_PLATNOSCI, ID_SKUTER, ID_PRACOWNIK, CENA, 
DATA_WYPOZYCZENIA DATE "YYYY-MM-DD", 
DATA_ODDANIA  DATE "YYYY-MM-DD")
